export const jobData = [
  {
    id: 1,
    jobTitle: "Business Developer Intern",
    location: "Remote",
    jobType: "Internship (Full-time)",
    duration: "3 months",
    companyOverview:
      "SmartCard AI operates at the intersection of artificial intelligence and data analytics, providing tools that facilitate efficient data retrieval and analysis. By utilizing LLMs, SmartCard AI enhances the capability of organizations to query complex datasets effortlessly, transforming raw data into actionable insights. This approach not only streamlines the decision-making process but also empowers users to extract meaningful information from vast amounts of unstructured data.",
    jobOverview:
      "We are looking for a dynamic Business Developer Intern with an MBA or BCA background who has strong communication skills, experience in cold calling, and a good understanding of the data analytics market. The ideal candidate should be proficient in business analytics tools like Power BI and eager to contribute to business growth through market research, lead generation, and client outreach.",
    keyResponsibilities: [
      "Conduct cold calls to potential clients and generate business leads.",
      "Research and analyze the data analytics market to identify business opportunities.",
      "Develop and implement strategies to acquire new clients and partnerships.",
      "Use Power BI and other analytics tools to generate insights and reports for business development.",
      "Assist in sales pitches, client meetings, and follow-ups.",
      "Maintain and update CRM records for business tracking.",
      "Collaborate with the sales and marketing teams to create targeted campaigns.",
    ],
    requirements: [
      "Educational Qualification: MBA/BCA (or currently pursuing).",
      "Strong communication skills in English.",
      "Experience in cold calling, lead generation, or sales is a plus.",
      "Good understanding of the data analytics market and industry trends.",
      "Knowledge of Power BI, Excel, or other data visualization tools.",
      "Self-motivated, goal-oriented, and proactive in business development.",
    ],
    preferredSkills: [
      "Familiarity with CRM tools (e.g., HubSpot, Salesforce).",
      "Basic knowledge of digital marketing and sales automation.",
      "Understanding of B2B sales and business analytics.",
    ],
    benefits: [
      "Hands-on experience in business development and analytics.",
      "Opportunity to work with industry experts and gain professional mentorship.",
      "Certificate of completion and potential for a full-time role based on performance.",
      "Networking opportunities with professionals in the data analytics industry.",
    ],
  },
  {
    id: 2,
    jobTitle: "Healthcare Data Analyst Intern",
    location: "Remote",
    jobType: "Internship (Full-time)",
    duration: "3 months",
    companyOverview:
      "SmartCard AI is a leader in artificial intelligence and data analytics, providing innovative solutions for healthcare organizations to analyze vast datasets and improve decision-making. By leveraging advanced technologies such as LLMs (Large Language Models), SmartCard AI helps transform unstructured data into actionable insights, enabling healthcare professionals to make data-driven decisions that improve patient care and operational efficiency.",
    jobOverview:
      "We are seeking a motivated Healthcare Data Analyst Intern to join our team. This role is perfect for individuals with a strong analytical background, an interest in healthcare data, and the ability to work with large datasets to derive insights. As an intern, you will contribute to data-driven decision-making by assisting with the collection, cleaning, and analysis of healthcare data. You will also work closely with the analytics team to develop reports and dashboards to help improve healthcare operations and patient outcomes.",
    keyResponsibilities: [
      "Assist in collecting, cleaning, and organizing healthcare data from multiple sources.",
      "Analyze large healthcare datasets to identify trends, patterns, and actionable insights.",
      "Support the development of data visualization reports and dashboards using tools like Power BI, Excel, and others.",
      "Collaborate with senior analysts to provide insights and recommendations that enhance operational efficiency and patient care.",
      "Conduct research on healthcare trends and assist with benchmarking key performance indicators (KPIs).",
      "Provide analytical support for ongoing healthcare projects, including predictive modeling and trend analysis.",
      "Present findings and results in a clear, concise manner to both technical and non-technical stakeholders.",
    ],
    requirements: [
      "Educational Qualification: Pursuing or recently completed a degree in Data Science, Healthcare Analytics, Public Health, or a related field.",
      "Strong proficiency in data analysis tools such as Excel, Power BI, or other visualization tools.",
      "Basic understanding of healthcare data and terminology.",
      "Strong analytical thinking, attention to detail, and problem-solving abilities.",
      "Ability to work independently and manage multiple tasks in a fast-paced environment.",
      "Excellent communication skills in English, both written and verbal.",
    ],
    preferredSkills: [
      "Knowledge of healthcare data sources such as electronic health records (EHR), claims data, or patient survey data.",
      "Familiarity with statistical analysis software (e.g., R, Python, SAS).",
      "Experience with data cleaning and data transformation techniques.",
      "Interest in healthcare trends, digital health, and analytics in the healthcare industry.",
    ],
    benefits: [
      "Hands-on experience in healthcare data analytics.",
      "Opportunity to work with a dynamic team of experts in AI and healthcare data.",
      "Mentorship and guidance from experienced professionals in the field.",
      "Certificate of completion and the potential for a full-time position based on performance.",
      "Networking opportunities with healthcare professionals and data analytics experts.",
    ],
  },
  {
    id: 3,
    jobTitle: "Financial Data Analyst Intern",
    location: "Remote",
    jobType: "Internship (Full-time)",
    duration: "3 months",
    companyOverview:
      "SmartCard AI is a leading innovator at the intersection of artificial intelligence and data analytics, offering cutting-edge solutions to organizations in the financial industry. By utilizing advanced AI technologies like Large Language Models (LLMs), SmartCard AI enables businesses to extract valuable insights from complex financial datasets. Our tools help clients streamline decision-making, optimize performance, and gain a competitive edge by turning raw data into actionable intelligence.",
    jobOverview:
      "We are looking for a detail-oriented and analytical Financial Data Analyst Intern to join our growing team. In this role, you will assist in analyzing financial datasets, providing insights into trends and performance metrics, and helping create reports that guide business decisions. This internship is perfect for someone interested in finance, data analysis, and working with financial data to drive strategy and business growth.",
    keyResponsibilities: [
      "Assist in collecting, cleaning, and organizing financial data from various sources.",
      "Analyze financial datasets to identify trends, patterns, and key performance indicators (KPIs).",
      "Support the creation of data visualizations, reports, and dashboards using tools like Excel, Power BI, or other analytics tools.",
      "Collaborate with senior financial analysts to develop insights that inform business decisions, optimize performance, and improve profitability.",
      "Conduct research on financial market trends and provide analysis to support forecasting and budgeting activities.",
      "Help with financial modeling and scenario analysis to support strategic planning.",
      "Present analytical findings in a clear and actionable format to both technical and non-technical stakeholders.",
    ],
    requirements: [
      "Educational Qualification: Pursuing or recently completed a degree in Finance, Economics, Data Science, or a related field.",
      "Strong proficiency in data analysis tools such as Excel, Power BI, or other financial analysis tools.",
      "Strong analytical and problem-solving skills, with an ability to work with large datasets.",
      "Ability to communicate complex financial concepts clearly and concisely.",
      "Detail-oriented, with the ability to manage multiple tasks in a fast-paced environment.",
      "Excellent communication skills in English, both written and verbal.",
    ],
    preferredSkills: [
      "Knowledge of financial data sources such as income statements, balance sheets, and cash flow reports.",
      "Familiarity with financial modeling and forecasting techniques.",
      "Experience with statistical software (e.g., R, Python, or similar tools).",
      "Understanding of financial markets, investment strategies, and economic trends.",
    ],
    benefits: [
      "Hands-on experience in financial data analysis and reporting.",
      "Opportunity to work with a dynamic team of experts in AI and financial analytics.",
      "Mentorship and professional development from experienced professionals in the finance and analytics fields.",
      "Certificate of completion and the potential for a full-time role based on performance.",
      "Networking opportunities with finance professionals and data analytics experts.",
    ],
  },
  {
    id: 4,
    jobTitle: "Python Backend Developer Intern",
    location: "Remote",
    jobType: "Internship (Full-time)",
    duration: "3 months",
    companyOverview:
      "SmartCard AI is at the forefront of artificial intelligence and data analytics, providing innovative solutions that transform complex datasets into actionable insights. By leveraging advanced technologies such as Large Language Models (LLMs), we empower organizations to make data-driven decisions more efficiently. Our team is passionate about utilizing AI to create impactful, scalable tools that drive business success.",
    jobOverview:
      "We are looking for a proactive Python Backend Developer Intern to join our development team. This internship will offer hands-on experience in backend development using Python, Flask, and integration with frontend technologies such as Electron.js, JavaScript, and HTML. You will also gain experience in deployment to cPanel, MySQL database management, and the testing and debugging process, ensuring smooth and reliable application performance across the stack.",
    keyResponsibilities: [
      "Assist in the development and maintenance of backend services using Python and Flask.",
      "Develop and integrate RESTful APIs to communicate with frontend applications built with Electron.js and JavaScript.",
      "Assist with deployment of backend applications to cPanel for hosting and production environments.",
      "Work with MySQL databases to manage, query, and store application data efficiently.",
      "Collaborate with frontend developers to integrate backend services with the user interface.",
      "Perform testing, debugging, and troubleshooting to ensure the application’s reliability and functionality.",
      "Participate in code reviews and help improve code quality by following best practices.",
      "Ensure the performance, scalability, and security of backend systems.",
      "Write clear, maintainable, and efficient code, and assist in documentation.",
      "Assist in building automated testing and deployment pipelines.",
    ],
    requirements: [
      "Educational Qualification: Pursuing or recently completed a degree in Computer Science, Software Engineering, or a related field.",
      "Strong proficiency in Python and Flask for backend development.",
      "Experience with frontend technologies such as Electron.js, JavaScript, and HTML.",
      "Familiarity with deploying applications to cPanel or similar hosting environments.",
      "Experience working with MySQL databases for storing and retrieving data.",
      "Knowledge of version control systems like Git.",
      "Strong problem-solving skills and the ability to work independently.",
      "Good communication skills in English, both written and verbal.",
    ],
    preferredSkills: [
      "Experience in developing and deploying RESTful APIs using Flask or similar frameworks.",
      "Familiarity with MySQL database management, including query optimization and schema design.",
      "Experience with deployment processes, especially in cPanel or similar hosting environments.",
      "Knowledge of debugging and testing techniques, including unit tests and integration testing.",
      "Understanding of security best practices in web application development.",
      "Familiarity with cloud platforms like AWS, Azure, or Google Cloud.",
      "Experience with containerization tools like Docker.",
    ],
    benefits: [
      "Hands-on experience in backend development with Python, Flask, and frontend integration with Electron.js and JavaScript.",
      "Exposure to deployment processes on cPanel and working with MySQL databases.",
      "Practical experience in testing, debugging, and improving application reliability.",
      "Mentorship and professional development from experienced engineers.",
      "Certificate of completion and the potential for a full-time role based on performance.",
      "Networking opportunities with professionals in software development and AI.",
    ],
  },
  {
    id: 5,
    jobTitle: "Project Delivery Management Intern",
    location: "Remote",
    jobType: "Internship (Full-time)",
    duration: "3 months",
    companyOverview:
      "SmartCard AI is an innovative company at the intersection of artificial intelligence and data analytics, delivering cutting-edge solutions to help organizations make data-driven decisions. We work with diverse industries to turn complex data into actionable insights, empowering businesses to optimize operations and enhance decision-making processes. Our team is passionate about leveraging AI and data analytics to drive impactful results.",
    jobOverview:
      "We are looking for a highly organized and proactive Project Delivery Management Intern to join our team. This role offers an excellent opportunity to work closely with experienced project managers and learn the ins and outs of managing the delivery of projects from start to finish. As an intern, you will assist in tracking project timelines, coordinating resources, communicating with stakeholders, and ensuring the successful delivery of projects according to client requirements and deadlines.",
    keyResponsibilities: [
      "Assist in the planning, execution, and delivery of projects within established timelines and budgets.",
      "Track and monitor project progress, helping to ensure deadlines are met and goals are achieved.",
      "Help with resource allocation and ensure that team members have the necessary tools and information to execute their tasks.",
      "Support communication between stakeholders, including clients, team members, and management.",
      "Assist in identifying potential project risks and help in devising strategies to mitigate them.",
      "Organize project meetings, prepare agendas, and take meeting notes to ensure all key actions are tracked.",
      "Help maintain project documentation and ensure all necessary records are up-to-date and accessible.",
      "Monitor project performance and provide regular updates to team members and management.",
      "Contribute to the preparation of project reports, presentations, and post-project evaluations.",
    ],
    requirements: [
      "Educational Qualification: Pursuing or recently completed a degree in Business Administration, Project Management, or a related field.",
      "Strong organizational skills and attention to detail.",
      "Ability to manage multiple tasks and prioritize effectively.",
      "Good communication skills, both written and verbal.",
      "Proactive and self-motivated with the ability to work independently.",
      "Basic understanding of project management methodologies (e.g., Agile, Waterfall).",
      "Familiarity with project management tools like Trello, Asana, or Microsoft Project is a plus.",
      "Ability to work collaboratively in a fast-paced environment.",
    ],
    preferredSkills: [
      "Experience with project coordination or managing projects in a team environment (internships or academic projects).",
      "Understanding of project lifecycle and how to deliver projects on time and within scope.",
      "Knowledge of risk management, budgeting, and scheduling principles.",
      "Interest in AI, data analytics, and technology-driven solutions.",
    ],
    benefits: [
      "Hands-on experience in project management and delivery coordination.",
      "Exposure to different project management methodologies and tools.",
      "Mentorship and guidance from experienced project managers.",
      "Certificate of completion and the potential for a full-time role based on performance.",
      "Networking opportunities with professionals in project management and AI.",
    ],
  },
  {
    id: 6,
    jobTitle: "Business Analyst",
    location: "Remote",
    jobType: "Full-time",
    duration: "Permanent",
    companyOverview:
      "SmartCard AI is a leader in artificial intelligence and data analytics, providing innovative solutions to help organizations unlock insights from complex data. Our products are designed to enable businesses to make smarter, data-driven decisions, enhancing operational efficiency and customer satisfaction. We work with industries such as healthcare, finance, and technology, transforming raw data into actionable intelligence using cutting-edge AI tools.",
    jobOverview:
      "We are seeking a detail-oriented and analytical Business Analyst to join our team. In this role, you will work closely with stakeholders to understand business needs, analyze data, and provide actionable insights that drive decision-making and strategic initiatives. You will gather and analyze business requirements, document processes, and support the development of solutions that optimize business operations.",
    keyResponsibilities: [
      "Collaborate with business stakeholders to understand their needs and translate them into clear business requirements.",
      "Analyze business processes, identify inefficiencies, and recommend improvements.",
      "Gather, document, and prioritize business requirements and ensure alignment with organizational goals.",
      "Perform data analysis, identifying trends and patterns to provide actionable insights to management and business teams.",
      "Create and maintain detailed business process models, use cases, and user stories.",
      "Collaborate with product managers, developers, and other stakeholders to ensure that solutions meet business needs and requirements.",
      "Develop and present reports, dashboards, and presentations to stakeholders, summarizing key findings and recommendations.",
      "Support the implementation of new systems or processes, ensuring successful adoption across the organization.",
      "Assist in testing new systems or enhancements to ensure that they meet business requirements and function as expected.",
      "Monitor and assess the performance of implemented solutions and recommend improvements.",
    ],
    requirements: [
      "Educational Qualification: Bachelor’s degree in Business Administration, Economics, Data Science, or a related field.",
      "Proven experience as a Business Analyst or in a similar role.",
      "Strong analytical skills with the ability to analyze complex data and provide insights.",
      "Proficiency in Microsoft Excel, Power BI, and other data visualization tools.",
      "Excellent communication skills, with the ability to present technical information to non-technical stakeholders.",
      "Strong problem-solving skills and the ability to work independently and in a team environment.",
      "Knowledge of business process modeling and requirements gathering techniques.",
      "Familiarity with Agile and Waterfall project management methodologies.",
    ],
    preferredSkills: [
      "Experience with business intelligence tools (e.g., Tableau, Power BI).",
      "Knowledge of SQL for querying databases and generating reports.",
      "Familiarity with data analysis tools (e.g., R, Python) is a plus.",
      "Experience in the AI, technology, or financial sectors is a plus.",
      "Certification in business analysis (e.g., CBAP, CCBA) is a plus.",
    ],
    benefits: [
      "Opportunity to work in a dynamic, fast-paced environment with cutting-edge technology.",
      "Competitive salary and benefits package.",
      "Professional development and career growth opportunities.",
      "Collaborative and innovative team culture.",
      "Flexible working hours and remote work options.",
    ],
  },
  {
    id: 7,
    jobTitle: "Sales Engineer Intern",
    location: "Remote",
    jobType: "Internship (Full-time)",
    duration: "3 months",
    companyOverview:
      "SmartCard AI is an industry leader in artificial intelligence and data analytics solutions, empowering organizations to unlock the full potential of their data. Through our innovative AI-driven products, we help businesses across various industries transform complex datasets into actionable insights. By combining advanced technologies like Large Language Models (LLMs) with user-friendly interfaces, we simplify data access, enhance decision-making, and optimize business operations.",
    jobOverview:
      "We are looking for a driven and technically-minded Sales Engineer Intern to join our dynamic sales team. In this role, you will support the sales process by helping to bridge the gap between our technical solutions and the needs of potential clients. You will work closely with both the sales and engineering teams to understand our products, provide technical support during the sales process, and help identify solutions that align with clients' needs. This internship will provide you with valuable experience in both technical sales and client-facing communication.",
    keyResponsibilities: [
      "Assist the sales team in presenting technical product solutions to potential clients.",
      "Help prepare and deliver product demonstrations and technical presentations to clients.",
      "Collaborate with engineering teams to understand product specifications and develop tailored solutions for clients.",
      "Provide technical support during the pre-sales process, including answering client questions and addressing technical concerns.",
      "Work closely with the sales team to create and customize proposals and presentations based on client requirements.",
      "Assist in preparing product documentation, including user guides and technical documentation.",
      "Gather and analyze customer feedback to improve product offerings and sales strategies.",
      "Support the creation and maintenance of technical materials for internal teams and client-facing assets.",
      "Participate in the creation of RFPs (Request for Proposals) and other technical sales documents.",
    ],
    requirements: [
      "Educational Qualification: Pursuing or recently completed a degree in Engineering, Computer Science, Information Technology, or a related field.",
      "Strong technical knowledge and interest in AI, data analytics, or software solutions.",
      "Excellent communication skills, both written and verbal, with the ability to explain complex technical concepts to non-technical stakeholders.",
      "Ability to work collaboratively in a team environment, with a strong focus on customer satisfaction.",
      "Detail-oriented, organized, and able to manage multiple tasks.",
      "Strong problem-solving skills and an eagerness to learn.",
      "Familiarity with CRM tools (e.g., Salesforce) is a plus.",
      "Experience with presentations, public speaking, or customer-facing communication is a plus.",
    ],
    preferredSkills: [
      "Knowledge of AI, machine learning, or data analytics concepts is a plus.",
      "Experience with technical product demos and client communication.",
      "Familiarity with the sales process and the role of a sales engineer in a tech-focused environment.",
      "Knowledge of technical documentation creation and proposal writing.",
    ],
    benefits: [
      "Hands-on experience in technical sales and product demonstrations.",
      "Exposure to AI-driven products and solutions in a fast-growing industry.",
      "Mentorship from experienced professionals in both technical and sales teams.",
      "Certificate of completion and potential for a full-time role based on performance.",
      "Networking opportunities with professionals in sales, engineering, and AI.",
    ],
  },
  {
    id: 8,
    jobTitle: "Sales Executive Intern",
    location: "Remote",
    jobType: "Internship (Full-time)",
    duration: "3 months",
    companyOverview:
      "SmartCard AI is a cutting-edge company specializing in artificial intelligence and data analytics solutions. We help businesses across various industries unlock valuable insights from complex datasets, enhancing decision-making, and driving business success. By leveraging AI-powered tools, we enable companies to transform raw data into actionable intelligence. We are committed to driving innovation and providing impactful solutions that simplify business processes and optimize performance.",
    jobOverview:
      "We are seeking a highly motivated and results-driven Sales Executive Intern to join our team. This role will offer you hands-on experience in the sales process, from lead generation to client relationship management. You will support the sales team by identifying potential customers, assisting in sales presentations, and contributing to business development efforts. This internship is perfect for someone eager to learn the ins and outs of sales and gain valuable exposure to the world of AI and data analytics.",
    keyResponsibilities: [
      "Conduct market research to identify new business opportunities and potential clients.",
      "Assist in generating and qualifying leads through various channels (e.g., cold calling, email outreach, and social media).",
      "Support the sales team in preparing sales presentations and product demos for potential clients.",
      "Help maintain and update CRM records with client information and sales activity.",
      "Participate in sales calls, meetings, and follow-ups to build strong customer relationships.",
      "Assist in creating and sending proposals, quotes, and contracts to clients.",
      "Monitor sales metrics and report progress to the sales manager.",
      "Contribute to sales strategy development by analyzing market trends and customer feedback.",
      "Assist with post-sales activities, ensuring smooth handovers to the customer success or account management teams.",
    ],
    requirements: [
      "Educational Qualification: Pursuing or recently completed a degree in Business Administration, Marketing, or a related field.",
      "Strong communication and interpersonal skills with the ability to engage clients effectively.",
      "Proactive and self-motivated, with a passion for sales and business development.",
      "Excellent organizational skills and the ability to manage multiple tasks.",
      "Familiarity with CRM tools (e.g., Salesforce, HubSpot) is a plus.",
      "Ability to work collaboratively in a fast-paced team environment.",
      "Basic understanding of business-to-business (B2B) sales strategies is a plus.",
    ],
    preferredSkills: [
      "Previous experience in sales, customer service, or business development (internships or part-time roles).",
      "Knowledge or interest in AI, data analytics, or technology solutions.",
      "Ability to work independently and take initiative.",
      "Experience with lead generation tools or sales outreach platforms is a plus.",
    ],
    benefits: [
      "Gain hands-on experience in sales and business development within a tech-focused industry.",
      "Learn from experienced sales professionals and receive mentorship.",
      "Develop valuable skills in client communication, sales presentations, and lead generation.",
      "Certificate of completion and potential for a full-time role based on performance.",
      "Networking opportunities with professionals in sales, marketing, and AI.",
    ],
  },
];
